-- APP2-DB01 — add the non-watermarked catalog preview derivative kind.
--
-- Generated by drizzle-kit from the `asset_derivatives` schema change, then
-- extended by hand with the two preflight guards this checkpoint requires
-- (same class as 0026/0030, which are hand-reviewed constraint/trigger DDL).
--
-- `CATALOG_PREVIEW` is the catalog display derivative of a CATALOG_MEDIA asset
-- (Admin/Storefront presentation, store-owned media, never watermarked). It is
-- deliberately NOT `PREVIEW_WATERMARKED` with `is_watermarked = false`: that
-- kind is the customer/design preview whose identity is the watermark
-- (INV-22, BR-012, ADR-APP2-001 §4.7 public preview contract).
--
-- No table, column, state, uniqueness or READY/storage-key behaviour changes.
-- Existing kinds are preserved and no historical row is rewritten.
--
-- The runner applies each migration exactly once inside a transaction, so the
-- window in which `ck_asset_derivatives__kind_allowed` is absent is not visible
-- to any other session — and the first ALTER already holds ACCESS EXCLUSIVE on
-- the table. Adding a CHECK validates existing rows with a scan; it does not
-- rewrite the table.

-- Preflight 1 — every stored kind must survive the replacement constraint.
-- A value outside the new allowed set would be silently kept by the DROP and
-- then rejected by the ADD, failing the migration with a bare 23514 that names
-- no row; this fails first, and says what it found.
DO $$
DECLARE
  offending text;
BEGIN
  SELECT string_agg(DISTINCT kind, ', ' ORDER BY kind)
    INTO offending
    FROM asset_derivatives
   WHERE kind NOT IN ('PREVIEW_WATERMARKED', 'MOCKUP', 'NORMALIZED', 'THUMBNAIL', 'CATALOG_PREVIEW');

  IF offending IS NOT NULL THEN
    RAISE EXCEPTION
      'APP2-DB01 preflight: asset_derivatives holds kind value(s) outside the new allowed set: %',
      offending;
  END IF;
END
$$;--> statement-breakpoint

-- Preflight 2 — existing rows must already satisfy the watermark invariant.
-- INV-22 has been application-enforced only until now, so this is the first
-- moment the data is actually checked. Counts only: a row id is not needed to
-- decide, and this message goes to migration output.
DO $$
DECLARE
  bad_watermarked bigint;
  bad_catalog bigint;
BEGIN
  SELECT count(*) INTO bad_watermarked
    FROM asset_derivatives
   WHERE kind = 'PREVIEW_WATERMARKED' AND is_watermarked <> true;

  SELECT count(*) INTO bad_catalog
    FROM asset_derivatives
   WHERE kind = 'CATALOG_PREVIEW' AND is_watermarked <> false;

  IF bad_watermarked > 0 OR bad_catalog > 0 THEN
    RAISE EXCEPTION
      'APP2-DB01 preflight: % PREVIEW_WATERMARKED row(s) without a watermark and % CATALOG_PREVIEW row(s) with one; ck_asset_derivatives__watermark_by_kind cannot be added until these are reconciled',
      bad_watermarked, bad_catalog;
  END IF;
END
$$;--> statement-breakpoint

ALTER TABLE "asset_derivatives" DROP CONSTRAINT "ck_asset_derivatives__kind_allowed";--> statement-breakpoint
ALTER TABLE "asset_derivatives" ADD CONSTRAINT "ck_asset_derivatives__watermark_by_kind" CHECK (("asset_derivatives"."kind" <> 'PREVIEW_WATERMARKED' or "asset_derivatives"."is_watermarked" = true) and ("asset_derivatives"."kind" <> 'CATALOG_PREVIEW' or "asset_derivatives"."is_watermarked" = false));--> statement-breakpoint
ALTER TABLE "asset_derivatives" ADD CONSTRAINT "ck_asset_derivatives__kind_allowed" CHECK ("asset_derivatives"."kind" in ('PREVIEW_WATERMARKED', 'MOCKUP', 'NORMALIZED', 'THUMBNAIL', 'CATALOG_PREVIEW'));
