-- APP3-DB01 — placement stable identity/retirement (IMP-D041) and canonical
-- asset-derivative output metadata (IMP-D044).
--
-- Generated by drizzle-kit from the schema change, then extended by hand with
-- the ordered backfill and the two guard trigger families — same class as
-- 0030_add_integrity_triggers.sql (hand-authored trigger DDL, which Drizzle's
-- table DSL cannot express) and 0032 (generated DDL plus hand-written preflight).
--
-- Two contribution groups, one forward-only migration:
--
--   A. `product_sides` / `embroidery_areas` gain `code`, `retired_at` and
--      `superseded_by_id`. A referenced placement is never edited in place and
--      never hard-deleted; it is retired and superseded by a replacement row.
--      That is only meaningful if the thing a Template, Session or snapshot
--      *means* survives the replacement — hence a stable `code` that is not the
--      display `name`.
--
--   B. `asset_derivatives` gains `width_px`, `height_px`, `media_type` and
--      `byte_size`: the canonical output metadata of that exact row. The
--      Studio may not guess dimensions, and `assets.mime_type` / `size_bytes`
--      describe the *source* binary, not the derivative.
--
-- No network call, no object-storage call, no application dependency. The
-- runner applies each migration exactly once inside a transaction.

--> BEGIN GROUP A — placement stable identity

-- Step 1: add `code` nullable, so the backfill can run before the constraint.
ALTER TABLE "product_sides" ADD COLUMN "code" text;--> statement-breakpoint
ALTER TABLE "embroidery_areas" ADD COLUMN "code" text;--> statement-breakpoint

-- Step 2: deterministic backfill. `legacy-<uuid without hyphens>` is derived
-- from the row's own immutable id, so it is stable across reruns and rebuilds
-- and cannot collide inside a parent. It is deliberately NOT derived from
-- `name`: names are display copy — localized, edited, and duplicated across
-- Products — and a code derived from one would change meaning when the copy
-- changed. Rows authored after this migration supply a meaningful code.
UPDATE "product_sides"
   SET "code" = 'legacy-' || replace("id"::text, '-', '')
 WHERE "code" IS NULL;--> statement-breakpoint
UPDATE "embroidery_areas"
   SET "code" = 'legacy-' || replace("id"::text, '-', '')
 WHERE "code" IS NULL;--> statement-breakpoint

-- Step 3: prove the backfill before trusting it. Without this, a null, a
-- duplicate or a format failure surfaces as a bare 23502/23505/23514 naming no
-- row, on a statement that is not the one that caused it.
DO $$
DECLARE
  v_null bigint;
  v_dup bigint;
  v_format bigint;
BEGIN
  SELECT count(*) INTO v_null FROM product_sides WHERE code IS NULL;
  SELECT count(*) INTO v_dup FROM (
    SELECT product_id, code FROM product_sides GROUP BY 1, 2 HAVING count(*) > 1
  ) d;
  SELECT count(*) INTO v_format
    FROM product_sides WHERE code !~ '^[a-z0-9][a-z0-9_-]{0,63}$';
  IF v_null > 0 OR v_dup > 0 OR v_format > 0 THEN
    RAISE EXCEPTION
      'APP3-DB01 backfill: product_sides has % null, % duplicate-per-product and % malformed code value(s)',
      v_null, v_dup, v_format;
  END IF;

  SELECT count(*) INTO v_null FROM embroidery_areas WHERE code IS NULL;
  SELECT count(*) INTO v_dup FROM (
    SELECT product_side_id, code FROM embroidery_areas GROUP BY 1, 2 HAVING count(*) > 1
  ) d;
  SELECT count(*) INTO v_format
    FROM embroidery_areas WHERE code !~ '^[a-z0-9][a-z0-9_-]{0,63}$';
  IF v_null > 0 OR v_dup > 0 OR v_format > 0 THEN
    RAISE EXCEPTION
      'APP3-DB01 backfill: embroidery_areas has % null, % duplicate-per-side and % malformed code value(s)',
      v_null, v_dup, v_format;
  END IF;
END
$$;--> statement-breakpoint

-- Step 4: only now is NOT NULL safe.
ALTER TABLE "product_sides" ALTER COLUMN "code" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "embroidery_areas" ALTER COLUMN "code" SET NOT NULL;--> statement-breakpoint

-- Step 5: retirement and replacement columns.
ALTER TABLE "product_sides" ADD COLUMN "retired_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "product_sides" ADD COLUMN "superseded_by_id" uuid;--> statement-breakpoint
ALTER TABLE "embroidery_areas" ADD COLUMN "retired_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "embroidery_areas" ADD COLUMN "superseded_by_id" uuid;--> statement-breakpoint

ALTER TABLE "product_sides" ADD CONSTRAINT "fk_product_sides__superseded_by_id" FOREIGN KEY ("superseded_by_id") REFERENCES "public"."product_sides"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "embroidery_areas" ADD CONSTRAINT "fk_embroidery_areas__superseded_by_id" FOREIGN KEY ("superseded_by_id") REFERENCES "public"."embroidery_areas"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint

-- Identity is unique per parent, never globally: two Products may both have a
-- `front`, and two Sides may both have a `chest`.
ALTER TABLE "product_sides" ADD CONSTRAINT "uq_product_sides__product_code" UNIQUE("product_id","code");--> statement-breakpoint
ALTER TABLE "embroidery_areas" ADD CONSTRAINT "uq_embroidery_areas__side_code" UNIQUE("product_side_id","code");--> statement-breakpoint

ALTER TABLE "product_sides" ADD CONSTRAINT "ck_product_sides__code_format" CHECK ("product_sides"."code" ~ '^[a-z0-9][a-z0-9_-]{0,63}$');--> statement-breakpoint
ALTER TABLE "product_sides" ADD CONSTRAINT "ck_product_sides__superseded_requires_retired" CHECK ("product_sides"."superseded_by_id" is null or "product_sides"."retired_at" is not null);--> statement-breakpoint
ALTER TABLE "product_sides" ADD CONSTRAINT "ck_product_sides__superseded_not_self" CHECK ("product_sides"."superseded_by_id" is null or "product_sides"."superseded_by_id" <> "product_sides"."id");--> statement-breakpoint
ALTER TABLE "embroidery_areas" ADD CONSTRAINT "ck_embroidery_areas__code_format" CHECK ("embroidery_areas"."code" ~ '^[a-z0-9][a-z0-9_-]{0,63}$');--> statement-breakpoint
ALTER TABLE "embroidery_areas" ADD CONSTRAINT "ck_embroidery_areas__superseded_requires_retired" CHECK ("embroidery_areas"."superseded_by_id" is null or "embroidery_areas"."retired_at" is not null);--> statement-breakpoint
ALTER TABLE "embroidery_areas" ADD CONSTRAINT "ck_embroidery_areas__superseded_not_self" CHECK ("embroidery_areas"."superseded_by_id" is null or "embroidery_areas"."superseded_by_id" <> "embroidery_areas"."id");--> statement-breakpoint

-- Step 6: the cross-row half of the replacement rule.
--
-- Self-replacement and "pointer without retirement" are single-row facts and
-- are CHECKs above. Same-parent and cycle are not: they need the *other* row,
-- which a CHECK may not read. One function serves both tables; TG_ARGV[0] names
-- the parent column.
--
-- Only the direct two-row cycle is rejected, as ruled. A longer chain is a
-- history, not a contradiction: a → b → c is exactly what two successive
-- replacements look like, and a generic graph walk here would reject it.
CREATE OR REPLACE FUNCTION public.fn_app3_placement_replacement_guard()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_parent_column text := TG_ARGV[0];
  v_new_parent text;
  v_target_parent text;
  v_target_superseded uuid;
  v_found boolean;
BEGIN
  IF NEW.superseded_by_id IS NULL THEN
    RETURN NEW;
  END IF;

  v_new_parent := to_jsonb(NEW) ->> v_parent_column;

  EXECUTE format(
    'SELECT true, (%I)::text, superseded_by_id FROM %I WHERE id = $1',
    v_parent_column, TG_TABLE_NAME
  )
  INTO v_found, v_target_parent, v_target_superseded
  USING NEW.superseded_by_id;

  IF NOT coalesce(v_found, false) THEN
    RAISE EXCEPTION
      'placement replacement violation: % row % names a replacement that does not exist',
      TG_TABLE_NAME, NEW.id
      USING ERRCODE = '23000';
  END IF;

  IF v_target_parent IS DISTINCT FROM v_new_parent THEN
    RAISE EXCEPTION
      'placement replacement violation: % row % may only be superseded within the same %',
      TG_TABLE_NAME, NEW.id, v_parent_column
      USING ERRCODE = '23000';
  END IF;

  IF v_target_superseded = NEW.id THEN
    RAISE EXCEPTION
      'placement replacement violation: % rows % and % supersede each other',
      TG_TABLE_NAME, NEW.id, NEW.superseded_by_id
      USING ERRCODE = '23000';
  END IF;

  RETURN NEW;
END
$$;--> statement-breakpoint

CREATE TRIGGER tg_product_sides__replacement_guard
BEFORE INSERT OR UPDATE ON "product_sides"
FOR EACH ROW EXECUTE FUNCTION public.fn_app3_placement_replacement_guard('product_id');--> statement-breakpoint

CREATE TRIGGER tg_embroidery_areas__replacement_guard
BEFORE INSERT OR UPDATE ON "embroidery_areas"
FOR EACH ROW EXECUTE FUNCTION public.fn_app3_placement_replacement_guard('product_side_id');--> statement-breakpoint

-- Step 7: referenced-row protection.
--
-- A placement becomes protected the moment a Template header scopes to it, a
-- non-terminal Design Session sits on it, or an approval snapshot froze it.
-- From then on its identity and geometry are what those rows *mean*, and an
-- in-place edit would silently rewrite their meaning. Retirement plus a
-- replacement row is the sanctioned way to change it; display copy, ordering
-- and the retirement pointers themselves stay editable, because none of them
-- changes what was referenced.
--
-- This lives in the database, not the repository, for the same reason S24 does:
-- an application-only guard is bypassed by every path that is not that
-- application.
CREATE OR REPLACE FUNCTION public.fn_app3_reject_protected_placement_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_entity text := TG_ARGV[0];
  v_protected_columns text[] := TG_ARGV[1:TG_NARGS - 1];
  v_row record := CASE TG_OP WHEN 'DELETE' THEN OLD ELSE OLD END;
  v_protected boolean;
  v_old jsonb;
  v_new jsonb;
  v_changed text;
BEGIN
  IF v_entity = 'product_side' THEN
    SELECT
      EXISTS (SELECT 1 FROM design_templates t WHERE t.product_side_id = v_row.id)
      OR EXISTS (
        SELECT 1 FROM design_sessions s
         WHERE s.product_side_id = v_row.id AND s.status NOT IN ('EXPIRED', 'DELETED')
      )
      OR EXISTS (SELECT 1 FROM approval_snapshots a WHERE a.product_side_id = v_row.id)
      INTO v_protected;
  ELSE
    SELECT
      EXISTS (SELECT 1 FROM design_templates t WHERE t.embroidery_area_id = v_row.id)
      OR EXISTS (
        SELECT 1 FROM design_sessions s
         WHERE s.embroidery_area_id = v_row.id AND s.status NOT IN ('EXPIRED', 'DELETED')
      )
      OR EXISTS (SELECT 1 FROM approval_snapshots a WHERE a.embroidery_area_id = v_row.id)
      INTO v_protected;
  END IF;

  IF NOT v_protected THEN
    RETURN CASE TG_OP WHEN 'DELETE' THEN OLD ELSE NEW END;
  END IF;

  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION
      'placement protection violation: % row % is referenced by a Template, a non-terminal Design Session or an approval snapshot and cannot be deleted; retire it instead',
      TG_TABLE_NAME, OLD.id
      USING ERRCODE = '23000';
  END IF;

  v_old := to_jsonb(OLD);
  v_new := to_jsonb(NEW);

  SELECT string_agg(key, ', ' ORDER BY key) INTO v_changed
  FROM unnest(v_protected_columns) AS key
  WHERE (v_old -> key) IS DISTINCT FROM (v_new -> key);

  IF v_changed IS NOT NULL THEN
    RAISE EXCEPTION
      'placement protection violation: % row % is referenced; identity/geometry column(s) % cannot change, use retirement and a replacement row',
      TG_TABLE_NAME, OLD.id, v_changed
      USING ERRCODE = '23000';
  END IF;

  RETURN NEW;
END
$$;--> statement-breakpoint

CREATE TRIGGER tg_product_sides__protected_guard
BEFORE UPDATE OR DELETE ON "product_sides"
FOR EACH ROW EXECUTE FUNCTION public.fn_app3_reject_protected_placement_change(
  'product_side',
  'product_id', 'code', 'background_asset_id', 'image_width_px', 'image_height_px',
  'physical_width_mm', 'physical_height_mm', 'px_per_mm'
);--> statement-breakpoint

CREATE TRIGGER tg_embroidery_areas__protected_guard
BEFORE UPDATE OR DELETE ON "embroidery_areas"
FOR EACH ROW EXECUTE FUNCTION public.fn_app3_reject_protected_placement_change(
  'embroidery_area',
  'product_side_id', 'code', 'bound_x_px', 'bound_y_px', 'bound_width_px',
  'bound_height_px', 'max_width_mm', 'max_height_mm'
);--> statement-breakpoint

--> BEGIN GROUP B — canonical derivative output metadata

ALTER TABLE "asset_derivatives" ADD COLUMN "width_px" integer;--> statement-breakpoint
ALTER TABLE "asset_derivatives" ADD COLUMN "height_px" integer;--> statement-breakpoint
ALTER TABLE "asset_derivatives" ADD COLUMN "media_type" text;--> statement-breakpoint
ALTER TABLE "asset_derivatives" ADD COLUMN "byte_size" bigint;--> statement-breakpoint

-- Preflight — no READY NORMALIZED row may already exist without metadata, or
-- the eligibility CHECK below would fail with a bare 23514 naming no row.
-- Measured at authoring time: zero NORMALIZED rows of any status exist.
DO $$
DECLARE
  v_blocking bigint;
BEGIN
  SELECT count(*) INTO v_blocking
    FROM asset_derivatives
   WHERE kind = 'NORMALIZED' AND status = 'READY';

  IF v_blocking > 0 THEN
    RAISE EXCEPTION
      'APP3-DB01 preflight: % READY NORMALIZED derivative row(s) exist with no canonical metadata; ck_asset_derivatives__ready_normalized_metadata cannot be added until they are measured. Values must never be fabricated (IMP-D044 PO-12)',
      v_blocking;
  END IF;
END
$$;--> statement-breakpoint

ALTER TABLE "asset_derivatives" ADD CONSTRAINT "ck_asset_derivatives__metadata_all_or_none" CHECK (num_nonnulls("asset_derivatives"."width_px", "asset_derivatives"."height_px", "asset_derivatives"."media_type", "asset_derivatives"."byte_size") in (0, 4));--> statement-breakpoint
ALTER TABLE "asset_derivatives" ADD CONSTRAINT "ck_asset_derivatives__metadata_positive" CHECK (("asset_derivatives"."width_px" is null or "asset_derivatives"."width_px" > 0) and ("asset_derivatives"."height_px" is null or "asset_derivatives"."height_px" > 0) and ("asset_derivatives"."byte_size" is null or "asset_derivatives"."byte_size" > 0) and ("asset_derivatives"."media_type" is null or btrim("asset_derivatives"."media_type", E' \t\r\n') <> ''));--> statement-breakpoint
ALTER TABLE "asset_derivatives" ADD CONSTRAINT "ck_asset_derivatives__ready_normalized_metadata" CHECK ("asset_derivatives"."kind" <> 'NORMALIZED' or "asset_derivatives"."status" <> 'READY' or num_nonnulls("asset_derivatives"."width_px", "asset_derivatives"."height_px", "asset_derivatives"."media_type", "asset_derivatives"."byte_size") = 4);
