-- APP5-DB01 — customer intake provenance on TBL-022 `assets`.
--
-- Generated by drizzle-kit from the schema change, then extended by hand with
-- the REL-106 foreign key — the same mechanism, and the same reason, as
-- `0010_add_deferred_session_fk.sql`: declaring the constraint in `assets.ts`
-- would close the module-import cycle
--
--     assets -> contact_verification_challenges -> design_sessions
--            -> product_sides -> assets
--
-- drizzle-kit diffs against its own snapshots, so a constraint it never saw is
-- neither dropped nor duplicated on a later generation.
--
-- ### Why this migration exists
--
-- `APP5-B02` (customer attachment intake) stopped as
-- `APP5_B02_PERSISTENT_INTAKE_PROVENANCE_REQUIRED`. `APP5-G01 D13` bounds
-- pre-submission intake to **20 accepted uploads per verified submission
-- challenge**, and `G01` §7 expires unbound uploads with that challenge's TTL
-- class. Nothing in the schema recorded which challenge authorized an upload:
-- `uploaded_by_customer_id` is a different scope (CST-007 uniqueness is per
-- `(contact_kind, normalized_value, purpose)`, so one customer can hold an
-- EMAIL and a PHONE `VERIFIED SUBMISSION` challenge at once) and
-- `uploaded_via_session_id` points at a design session the customer-owned-
-- product branch never has.
--
-- ### Why two columns and not one
--
-- The challenge family is **hard-TTL-deleted** and this FK is `SET NULL`. With
-- only the id, deletion would erase the future orphan sweep's due time along
-- with the pointer, and every unbound upload would become unreachable garbage.
-- `intake_expires_at` is the durable anchor: it is written from the
-- authoritative challenge expiry at intake and survives the parent's deletion.
-- That is also why the expiry CHECK is one-directional — see below.
--
-- Both columns are nullable, so no backfill exists and every APP1-APP4 asset
-- remains valid unchanged. No value is guessed for a historical row.
--
-- Forward-only. No down section, no rollback, no DROP. No network call, no
-- object-storage call, no application dependency. The runner applies each
-- migration exactly once inside a transaction.

ALTER TABLE "assets" ADD COLUMN "uploaded_via_challenge_id" uuid;--> statement-breakpoint
ALTER TABLE "assets" ADD COLUMN "intake_expires_at" timestamp with time zone;--> statement-breakpoint

-- REL-106 — assets -> contact_verification_challenges (hand-authored, see the
-- header). `ON DELETE SET NULL`, not `restrict`: the parent is a hard-TTL-
-- deleted `temp` table, exactly like the REL-033 session edge in 0010. Under
-- `restrict` the TTL sweep of a challenge would be blocked by every asset
-- uploaded under it — retention would stop working. Under `cascade` the asset
-- row (and with it the storage key of a binary that still exists) would vanish,
-- which INV-10 and the two-phase deletion contract forbid.
ALTER TABLE "assets"
  ADD CONSTRAINT "fk_assets__uploaded_via_challenge_id"
  FOREIGN KEY ("uploaded_via_challenge_id")
  REFERENCES "public"."contact_verification_challenges"("id")
  ON DELETE SET NULL ON UPDATE NO ACTION;--> statement-breakpoint

-- Quota access path (`G01-D13`). Leading key is the challenge, so one
-- challenge's rows form one contiguous range and the ACCEPTED count is a range
-- scan rather than a table scan; `status` follows so the count is answered from
-- the index alone. The predicate keeps the index to live intake rows.
CREATE INDEX "ix_assets__challenge_status__intake_live" ON "assets" USING btree ("uploaded_via_challenge_id","status") WHERE "assets"."uploaded_via_challenge_id" is not null and "assets"."deleted_at" is null;--> statement-breakpoint

-- Orphan due-time access path. The sweep SE-014/SE-015 will eventually run
-- finds due intake assets by time. `now()` stays in the query, never in the
-- predicate (DB6-S26 volatile-predicate rule).
CREATE INDEX "ix_assets__intake_expires_id__live" ON "assets" USING btree ("intake_expires_at","id") WHERE "assets"."intake_expires_at" is not null and "assets"."deleted_at" is null;--> statement-breakpoint

-- CST-127 — one intake lane per row. Both pointers set is not a stricter
-- record, it is two contradictory answers to "who authorized this byte", and
-- the per-challenge quota counts rows by exactly one of them.
ALTER TABLE "assets" ADD CONSTRAINT "ck_assets__single_intake_lane" CHECK (not ("assets"."uploaded_via_session_id" is not null and "assets"."uploaded_via_challenge_id" is not null));--> statement-breakpoint

-- CST-128 — the challenge lane must carry its own due time. The reverse
-- implication is deliberately NOT asserted: because the FK is `SET NULL` over a
-- hard-deleted parent, an expiry legitimately outlives the id that produced it.
-- Requiring a challenge id whenever the expiry is present would make the
-- parent's own TTL deletion violate this table's CHECK.
ALTER TABLE "assets" ADD CONSTRAINT "ck_assets__challenge_intake_requires_expiry" CHECK ("assets"."uploaded_via_challenge_id" is null or "assets"."intake_expires_at" is not null);
