-- APP12-DB01 — Ready-Made order origin, lifecycle, FULL payment obligation,
-- ORDER_ACCESS secure grants and expiring reservation persistence
-- (APP12-P01, APP12-G01 wave-1 scope).
--
-- Generated by drizzle-kit from the schema change, then extended by hand with
-- the data precheck, the ordered `origin` backfill, the cross-module foreign
-- key and the origin guard trigger family — same class as
-- 0030_add_integrity_triggers.sql (hand-authored trigger DDL, which Drizzle's
-- table DSL cannot express) and 0034 (generated DDL plus hand-written ordered
-- backfill and two guard trigger families).
--
-- ### Why this migration exists
--
-- APP12-P01 locked a second order shape: a Ready-Made order buys an existing
-- SKU. It has no custom request, no quotation, no approval snapshot, no
-- production job and no deposit/remaining split. Every one of those is
-- `NOT NULL` or structurally required today, because the DB era modelled the
-- only order that then existed. Making a Ready-Made order representable without
-- this migration would mean fabricating a request, a quotation and an approval
-- snapshot for a product bought off the shelf — evidence invented to satisfy a
-- constraint, which is the one thing this schema exists to prevent.
--
-- ### The shape — one discriminator, then origin-aware truth
--
-- `orders.origin` is the discriminator (`CUSTOM` | `READY_MADE`). It is the
-- only new column on `orders`, and it is immutable after insert
-- (`tg_orders__origin_immutable`): every rule below is evaluated against it,
-- and a mutable discriminator would let a committed row change what its
-- children were validated against.
--
-- The three custom-chain columns become nullable, but nothing is weakened: the
-- `NOT NULL` each of them lost is restored, conditionally, by
-- `ck_orders__custom_chain_by_origin`. A `CUSTOM` order still cannot exist
-- without its request, its accepted quotation version and its approval
-- snapshot; a `READY_MADE` order cannot carry any of them.
--
-- `uq_orders__request` is kept exactly as CST-030 wrote it. Postgres treats
-- NULLs as distinct in a UNIQUE index, so the one-order-per-request backstop
-- keeps its full strength for custom orders while every Ready-Made row (whose
-- `custom_request_id` is NULL) is simply not constrained by it. Replacing it
-- with a partial index would change nothing except the constraint's name.
--
-- ### Status: a union vocabulary, two lifecycles
--
-- `ck_orders__status_allowed` widens to thirteen values, but no order may hold
-- all thirteen. `ck_orders__origin_status_allowed` is the constraint that
-- carries the truth: `CUSTOM` keeps exactly the LC-14 eleven, and `READY_MADE`
-- may hold only `AWAITING_SHIPPING_FEE`, `AWAITING_PAYMENT`,
-- `READY_FOR_DELIVERY`, `DELIVERED`, `COMPLETED` and the three shared exception
-- states. A Ready-Made order can therefore never reach `AWAITING_DEPOSIT`,
-- `DEPOSIT_PAID`, `IN_PRODUCTION`, `PRODUCTION_COMPLETED` or
-- `AWAITING_FINAL_PAYMENT`, and a custom order can never reach the two new
-- states. No `PAID` state is added: "paid" is the obligation's fact (LC-15),
-- and a second copy of it on the order is exactly the derived-state duplication
-- DB4 refused.
--
-- `ck_order_transitions__{from,to}_status_allowed` widen to the same thirteen,
-- because a Ready-Made transition must be recordable in the audit table that
-- records every order move.
--
-- ### Cross-table integrity — one mechanism, not three
--
-- Three rules need a parent column no row CHECK can read:
--
--   order_items.approval_snapshot_id   required by CUSTOM, forbidden to READY_MADE
--   order_items subject                READY_MADE buys a SKU, never a COP
--   payment_obligations.kind           DEPOSIT/REMAINING is custom, FULL is Ready-Made
--
-- All three are enforced by one function, `fn_app12_order_origin_guard`,
-- dispatched by `TG_ARGV[0]`, in the shape 0030 and 0034 already established:
-- `SECURITY INVOKER`, `search_path` pinned, `to_jsonb(NEW)` field access so one
-- function can serve triggers on differently-shaped tables. `order_items`'
-- lost `NOT NULL` is therefore not a silently unconstrained nullable column —
-- it is a cross-table constraint, which is what the invariant always was.
--
-- The lookup is race-free without a constraint trigger: the child's own foreign
-- key to `orders` guarantees the parent row is visible to this transaction, and
-- `orders.origin` can never change, so a value read at INSERT stays true.
--
-- ### `origin` is deliberately NOT copied into the child tables
--
-- A denormalized `order_items.origin` / `payment_obligations.origin` would make
-- a plain CHECK sufficient and need no trigger — and would create a second,
-- mutable source for a fact that already has one. Two copies of a discriminator
-- that disagree is a worse failure than the one this migration prevents.
--
-- ### Payment
--
-- `kind` gains `FULL`; `DEPOSIT` and `REMAINING` are untouched in both name and
-- meaning. `source_quotation_version_id` becomes nullable because a FULL amount
-- is derived from the SKU price plus the frozen shipping fee and has no
-- quotation to name — and `ck_payment_obligations__source_by_kind` immediately
-- takes the `NOT NULL` back for the two custom kinds. A FULL obligation
-- carrying a quotation reference is rejected too: a fabricated derivation is
-- worse than a missing one.
--
-- `uq_payment_obligations__order_kind__live` is reused unchanged. It already
-- excludes `SUPERSEDED`, so the pre-payment shipping-fee correction chain
-- (PENDING → SUPERSEDED → successor PENDING) works for FULL exactly as it works
-- for REMAINING today. No index is added or altered.
--
-- ### Secure access
--
-- `scope_kind` gains `ORDER_ACCESS`, the second and last scope.
-- `custom_request_id` becomes nullable, `order_id` is added, and
-- `ck_secure_access_grants__scope_subject` makes the pair a typed XOR: a grant
-- with both subjects, with neither, or with the other scope's subject cannot be
-- stored. The `order_id` foreign key is added here rather than in the Drizzle
-- table because `approval_snapshots` imports `secure_access_grants` and `orders`
-- imports `approval_snapshots` — declaring it in the table module would close a
-- circular import, the same cycle class as REL-083's `satisfied_by_attempt_id`,
-- REL-044/0016 and REL-098/0019.
--
-- `uq_secure_access_grants__customer_order__active` is the ORDER_ACCESS half of
-- CST-009: the existing request index leads with a column that is NULL on every
-- order grant, and NULLs never collide, so without the parallel index a
-- customer could hold two ACTIVE grants on one order.
--
-- ### Reservations — representable, not yet enforced by origin
--
-- No DDL. `inventory_reservations.expires_at` is already nullable and
-- `ix_inventory_reservations__expires_id__reserved` already indexes exactly the
-- rows a sweeper reads (`RESERVED` and `expires_at IS NOT NULL`), so an
-- expiring Ready-Made reservation is representable today and needs no new
-- table, column or index.
--
-- An origin-conditional expiry rule is deliberately NOT added. `READY_MADE =>
-- expires_at IS NOT NULL` would forbid the legitimate post-payment move that
-- clears the window on a reservation which must now survive until dispatch, and
-- `CUSTOM => expires_at IS NULL` would freeze PO-APP8-002 — a reservation
-- *policy* — into DDL that only a migration could change. Both halves are
-- runtime invariants, assigned to APP12-B02 (set the 24h window at creation)
-- and APP12-B04/B05 (clear it on FULL satisfaction). Recorded as a residual in
-- the APP12-DB01 completion report §J, not left implicit.
--
-- ### Data
--
-- Every existing order becomes `CUSTOM`. There is no heuristic: no Ready-Made
-- order can exist before this migration, because nothing could represent one.
-- The backfill is a single unconditional UPDATE, run before `SET NOT NULL`,
-- with no column default at any point — a default would silently classify a
-- future insert that forgot to state its origin.
--
-- Nothing else is written: no obligation kind, no grant scope, no reservation
-- expiry and no order status is changed by this migration.
--
-- ### Generation note
--
-- `drizzle-kit generate` again emitted the spurious `DROP CONSTRAINT` /
-- re-`ADD` pair for `ck_approval_snapshots__preview_hash_format` that
-- APP6-DB01 §3.1 documented and APP7-DB01 predicted, with the re-add truncated
-- at `'^sha256:[0-9a-f]{64}` because the value contains the JavaScript
-- replacement pattern `$'`. Both statements were removed and the same corrupted
-- value was repaired in `meta/0038_snapshot.json` to the value
-- `0037_snapshot.json` records, which is the constraint actually installed —
-- nothing here alters it.

--> STEP 0 — data precheck.
--
-- The new conditional constraints are strictly stronger than the ones they
-- replace only if the existing data already satisfies the historical CUSTOM
-- authority. If it does not, this migration must fail loudly rather than
-- silently repair rows: a repair here would rewrite commercial evidence
-- unreviewed. Each count is over data this migration is about to constrain.
DO $$
DECLARE
  v_orders_missing_chain bigint;
  v_items_missing_approval bigint;
  v_obligations_bad_source bigint;
  v_grants_bad_subject bigint;
BEGIN
  SELECT count(*) INTO v_orders_missing_chain
    FROM orders
   WHERE custom_request_id IS NULL
      OR accepted_quotation_version_id IS NULL
      OR current_approval_snapshot_id IS NULL;

  SELECT count(*) INTO v_items_missing_approval
    FROM order_items WHERE approval_snapshot_id IS NULL;

  SELECT count(*) INTO v_obligations_bad_source
    FROM payment_obligations
   WHERE kind NOT IN ('DEPOSIT', 'REMAINING') OR source_quotation_version_id IS NULL;

  SELECT count(*) INTO v_grants_bad_subject
    FROM secure_access_grants
   WHERE scope_kind <> 'REQUEST_ACCESS' OR custom_request_id IS NULL;

  IF v_orders_missing_chain > 0
     OR v_items_missing_approval > 0
     OR v_obligations_bad_source > 0
     OR v_grants_bad_subject > 0 THEN
    RAISE EXCEPTION
      'APP12-DB01 precheck failed: % orders missing the custom chain, % order items missing an approval snapshot, % payment obligations with an invalid kind/source pair, % secure grants violating the REQUEST_ACCESS subject rule',
      v_orders_missing_chain, v_items_missing_approval,
      v_obligations_bad_source, v_grants_bad_subject
      USING ERRCODE = '23514';
  END IF;
END
$$;--> statement-breakpoint

--> STEP 1 — `orders.origin`: add nullable, backfill, enforce, never default.
ALTER TABLE "orders" ADD COLUMN "origin" text;--> statement-breakpoint

UPDATE "orders" SET "origin" = 'CUSTOM' WHERE "origin" IS NULL;--> statement-breakpoint

ALTER TABLE "orders" ALTER COLUMN "origin" SET NOT NULL;--> statement-breakpoint

ALTER TABLE "orders" ADD CONSTRAINT "ck_orders__origin_allowed" CHECK ("orders"."origin" in ('CUSTOM', 'READY_MADE'));--> statement-breakpoint

--> STEP 2 — the custom chain becomes conditional, not optional.
ALTER TABLE "orders" ALTER COLUMN "custom_request_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "orders" ALTER COLUMN "accepted_quotation_version_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "orders" ALTER COLUMN "current_approval_snapshot_id" DROP NOT NULL;--> statement-breakpoint

ALTER TABLE "orders" ADD CONSTRAINT "ck_orders__custom_chain_by_origin" CHECK (("orders"."origin" = 'CUSTOM' and "orders"."custom_request_id" is not null and "orders"."accepted_quotation_version_id" is not null and "orders"."current_approval_snapshot_id" is not null) or ("orders"."origin" = 'READY_MADE' and "orders"."custom_request_id" is null and "orders"."accepted_quotation_version_id" is null and "orders"."current_approval_snapshot_id" is null));--> statement-breakpoint

--> STEP 3 — status: widen the column vocabulary, then constrain it by origin.
ALTER TABLE "orders" DROP CONSTRAINT "ck_orders__status_allowed";--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "ck_orders__status_allowed" CHECK ("orders"."status" in ('AWAITING_DEPOSIT', 'DEPOSIT_PAID', 'IN_PRODUCTION', 'PRODUCTION_COMPLETED', 'AWAITING_FINAL_PAYMENT', 'READY_FOR_DELIVERY', 'DELIVERED', 'COMPLETED', 'ON_HOLD', 'CANCELLING', 'CANCELLED', 'AWAITING_SHIPPING_FEE', 'AWAITING_PAYMENT'));--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "ck_orders__origin_status_allowed" CHECK (("orders"."origin" = 'CUSTOM' and "orders"."status" in ('AWAITING_DEPOSIT', 'DEPOSIT_PAID', 'IN_PRODUCTION', 'PRODUCTION_COMPLETED', 'AWAITING_FINAL_PAYMENT', 'READY_FOR_DELIVERY', 'DELIVERED', 'COMPLETED', 'ON_HOLD', 'CANCELLING', 'CANCELLED')) or ("orders"."origin" = 'READY_MADE' and "orders"."status" in ('AWAITING_SHIPPING_FEE', 'AWAITING_PAYMENT', 'READY_FOR_DELIVERY', 'DELIVERED', 'COMPLETED', 'ON_HOLD', 'CANCELLING', 'CANCELLED')));--> statement-breakpoint

ALTER TABLE "order_transitions" DROP CONSTRAINT "ck_order_transitions__from_status_allowed";--> statement-breakpoint
ALTER TABLE "order_transitions" DROP CONSTRAINT "ck_order_transitions__to_status_allowed";--> statement-breakpoint
ALTER TABLE "order_transitions" ADD CONSTRAINT "ck_order_transitions__from_status_allowed" CHECK ("order_transitions"."from_status" in ('AWAITING_DEPOSIT', 'DEPOSIT_PAID', 'IN_PRODUCTION', 'PRODUCTION_COMPLETED', 'AWAITING_FINAL_PAYMENT', 'READY_FOR_DELIVERY', 'DELIVERED', 'COMPLETED', 'ON_HOLD', 'CANCELLING', 'CANCELLED', 'AWAITING_SHIPPING_FEE', 'AWAITING_PAYMENT'));--> statement-breakpoint
ALTER TABLE "order_transitions" ADD CONSTRAINT "ck_order_transitions__to_status_allowed" CHECK ("order_transitions"."to_status" in ('AWAITING_DEPOSIT', 'DEPOSIT_PAID', 'IN_PRODUCTION', 'PRODUCTION_COMPLETED', 'AWAITING_FINAL_PAYMENT', 'READY_FOR_DELIVERY', 'DELIVERED', 'COMPLETED', 'ON_HOLD', 'CANCELLING', 'CANCELLED', 'AWAITING_SHIPPING_FEE', 'AWAITING_PAYMENT'));--> statement-breakpoint

--> STEP 4 — order items: the approval snapshot becomes origin-conditional.
ALTER TABLE "order_items" ALTER COLUMN "approval_snapshot_id" DROP NOT NULL;--> statement-breakpoint

--> STEP 5 — payment obligations: `FULL`, and a kind-conditional source.
ALTER TABLE "payment_obligations" ALTER COLUMN "source_quotation_version_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "payment_obligations" DROP CONSTRAINT "ck_payment_obligations__kind_allowed";--> statement-breakpoint
ALTER TABLE "payment_obligations" ADD CONSTRAINT "ck_payment_obligations__kind_allowed" CHECK ("payment_obligations"."kind" in ('DEPOSIT', 'REMAINING', 'FULL'));--> statement-breakpoint
ALTER TABLE "payment_obligations" ADD CONSTRAINT "ck_payment_obligations__source_by_kind" CHECK (("payment_obligations"."kind" in ('DEPOSIT', 'REMAINING') and "payment_obligations"."source_quotation_version_id" is not null) or ("payment_obligations"."kind" = 'FULL' and "payment_obligations"."source_quotation_version_id" is null));--> statement-breakpoint

--> STEP 6 — secure access grants: the ORDER_ACCESS scope and its subject.
ALTER TABLE "secure_access_grants" ADD COLUMN "order_id" uuid;--> statement-breakpoint
ALTER TABLE "secure_access_grants" ALTER COLUMN "custom_request_id" DROP NOT NULL;--> statement-breakpoint

ALTER TABLE "secure_access_grants" ADD CONSTRAINT "fk_secure_access_grants__order_id" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint

ALTER TABLE "secure_access_grants" DROP CONSTRAINT "ck_secure_access_grants__scope_kind_allowed";--> statement-breakpoint
ALTER TABLE "secure_access_grants" ADD CONSTRAINT "ck_secure_access_grants__scope_kind_allowed" CHECK ("secure_access_grants"."scope_kind" in ('REQUEST_ACCESS', 'ORDER_ACCESS'));--> statement-breakpoint
ALTER TABLE "secure_access_grants" ADD CONSTRAINT "ck_secure_access_grants__scope_subject" CHECK (("secure_access_grants"."scope_kind" = 'REQUEST_ACCESS' and "secure_access_grants"."custom_request_id" is not null and "secure_access_grants"."order_id" is null) or ("secure_access_grants"."scope_kind" = 'ORDER_ACCESS' and "secure_access_grants"."order_id" is not null and "secure_access_grants"."custom_request_id" is null));--> statement-breakpoint

CREATE UNIQUE INDEX "uq_secure_access_grants__customer_order__active" ON "secure_access_grants" USING btree ("customer_id","order_id") WHERE "secure_access_grants"."status" = 'ACTIVE';--> statement-breakpoint
CREATE INDEX "ix_secure_access_grants__order_id" ON "secure_access_grants" USING btree ("order_id");--> statement-breakpoint

--> STEP 7 — the origin guard trigger family.
--
-- One function, three rules, selected by TG_ARGV[0]:
--   'origin_immutable'  — orders.origin never changes after insert
--   'item_subject'      — order_items approval/subject by parent origin
--   'obligation_kind'   — payment_obligations kind by parent origin
--
-- Fields are read through `to_jsonb(NEW)` rather than `NEW.<column>` so one
-- function can serve triggers on three differently-shaped tables — the access
-- shape 0030's freeze guard and 0034's placement guard already use.
CREATE OR REPLACE FUNCTION public.fn_app12_order_origin_guard()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_rule text := TG_ARGV[0];
  v_new jsonb := to_jsonb(NEW);
  v_old_origin text;
  v_order_id uuid;
  v_origin text;
BEGIN
  IF v_rule = 'origin_immutable' THEN
    v_old_origin := to_jsonb(OLD) ->> 'origin';
    IF v_old_origin IS DISTINCT FROM (v_new ->> 'origin') THEN
      RAISE EXCEPTION
        'order origin violation: orders.origin is immutable (% -> %)',
        v_old_origin, v_new ->> 'origin'
        USING ERRCODE = '23000';
    END IF;
    RETURN NEW;
  END IF;

  v_order_id := (v_new ->> 'order_id')::uuid;
  SELECT o.origin INTO v_origin FROM public.orders o WHERE o.id = v_order_id;

  IF v_origin IS NULL THEN
    -- Unreachable while the child's own foreign key to `orders` stands; raised
    -- rather than ignored so a future schema change cannot silently turn this
    -- guard into a pass.
    RAISE EXCEPTION
      'order origin violation: % row % names order %, which does not exist',
      TG_TABLE_NAME, v_new ->> 'id', v_order_id
      USING ERRCODE = '23503';
  END IF;

  IF v_rule = 'item_subject' THEN
    IF v_origin = 'CUSTOM' AND (v_new ->> 'approval_snapshot_id') IS NULL THEN
      RAISE EXCEPTION
        'order origin violation: order item % on CUSTOM order % requires approval_snapshot_id (D7-07)',
        v_new ->> 'id', v_order_id
        USING ERRCODE = '23000';
    END IF;

    IF v_origin = 'READY_MADE' THEN
      IF (v_new ->> 'approval_snapshot_id') IS NOT NULL THEN
        RAISE EXCEPTION
          'order origin violation: order item % on READY_MADE order % may not carry an approval snapshot',
          v_new ->> 'id', v_order_id
          USING ERRCODE = '23000';
      END IF;

      IF (v_new ->> 'sku_id') IS NULL THEN
        RAISE EXCEPTION
          'order origin violation: order item % on READY_MADE order % must name a SKU, never a customer-owned product',
          v_new ->> 'id', v_order_id
          USING ERRCODE = '23000';
      END IF;
    END IF;

    RETURN NEW;
  END IF;

  IF v_rule = 'obligation_kind' THEN
    IF v_origin = 'CUSTOM' AND (v_new ->> 'kind') NOT IN ('DEPOSIT', 'REMAINING') THEN
      RAISE EXCEPTION
        'order origin violation: payment obligation % on CUSTOM order % must be DEPOSIT or REMAINING, not %',
        v_new ->> 'id', v_order_id, v_new ->> 'kind'
        USING ERRCODE = '23000';
    END IF;

    IF v_origin = 'READY_MADE' AND (v_new ->> 'kind') <> 'FULL' THEN
      RAISE EXCEPTION
        'order origin violation: payment obligation % on READY_MADE order % must be FULL, not %',
        v_new ->> 'id', v_order_id, v_new ->> 'kind'
        USING ERRCODE = '23000';
    END IF;

    RETURN NEW;
  END IF;

  RAISE EXCEPTION 'order origin violation: unknown guard rule %', v_rule
    USING ERRCODE = '23000';
END
$$;--> statement-breakpoint

CREATE TRIGGER tg_orders__origin_immutable
BEFORE UPDATE ON "orders"
FOR EACH ROW EXECUTE FUNCTION public.fn_app12_order_origin_guard('origin_immutable');--> statement-breakpoint

CREATE TRIGGER tg_order_items__origin_subject
BEFORE INSERT OR UPDATE ON "order_items"
FOR EACH ROW EXECUTE FUNCTION public.fn_app12_order_origin_guard('item_subject');--> statement-breakpoint

CREATE TRIGGER tg_payment_obligations__origin_kind
BEFORE INSERT OR UPDATE ON "payment_obligations"
FOR EACH ROW EXECUTE FUNCTION public.fn_app12_order_origin_guard('obligation_kind');
