-- APP12-M01.DB1 — Product-media gallery invariants and the 20-image bound.
--
-- Generated by drizzle-kit from the schema change, then extended by hand with
-- the data precheck — the same shape as 0038, whose constraint work this
-- follows exactly.
--
-- ### Why this migration exists
--
-- `APP12-M01.A` audited the Product gallery and found the multi-image feature
-- already delivered at every layer; what the schema could not state was which
-- row is the gallery's primary. `product_media` guaranteed only that a
-- (product, asset, role) triple appeared once. It permitted the same Asset
-- twice in one Product under two roles, two rows at the same `display_order`,
-- a negative position, an unbounded position, a `THUMBNAIL` anywhere in the
-- strip, and a position 0 that is not the primary. Every public reader —
-- the card thumbnail, `media[0]`, `og:image` and the JSON-LD image list —
-- resolves the primary from exactly these columns, so each of those states is
-- a way for the four to disagree about the same Product.
--
-- `APP12-M01.B1` made the four agree by construction in the read path. This
-- migration makes the underlying rows incapable of the ambiguity in the first
-- place, so the guarantee does not depend on every future writer remembering
-- it.
--
-- ### The four constraints, and the two that are deliberately absent
--
--   uq_product_media__product_asset          one Asset per Product
--   uq_product_media__product_display_order  one row per position
--   ck_product_media__display_order_bounded  0 <= display_order < 20
--   ck_product_media__primary_role_at_zero   THUMBNAIL if and only if position 0
--
-- Two further rules are NOT installed here: that a non-empty selection
-- contains position 0, and that its positions are contiguous `0..N-1`. Both
-- are statements about a *set* of rows, which no row CHECK can read. A
-- constraint trigger written only so that "exactly one primary when media
-- exists" could be claimed of the database would fire on every intermediate
-- state of the Admin write, which legitimately deletes the whole selection and
-- re-inserts it inside one transaction — and 0030's guard family exists to
-- protect facts, not to re-implement an application's transaction shape. Those
-- two are the domain's (`ProductMediaSelection`), enforced before a single row
-- is written and proved there.
--
-- This is therefore a layered claim, and it is stated as one: the database
-- guarantees no duplicate Asset, no duplicate position, bounded positions and
-- the primary pinned to position 0; the domain guarantees the selection is
-- contiguous, contains position 0 and holds at most 20 items.
--
-- ### `uq_product_media__product_asset_role` is replaced, not dropped
--
-- CST-013 / IDX-015 keyed on (product_id, asset_id, role). Removing `role`
-- strictly tightens it: every pair the old key permitted the new key still
-- permits, except the one it existed to allow — the same Asset appearing twice
-- in one Product under two roles. The `product_id` prefix is unchanged, so the
-- media-by-product lookup IDX-015 has always served keeps its index, which is
-- why DB5's redundancy review rejected a separate ordering index (catalog
-- rejection entry R07) and why no index is added here.
--
-- ### The bound is 20, and it is written once
--
-- `MAX_PRODUCT_MEDIA_ITEMS` in `schema/catalog/product-media.ts` is the single
-- authority. The literal `20` below is rendered from it by drizzle-kit, the
-- domain cap reads it, the Admin request contract publishes it as `maxItems`,
-- and a parity test asserts all four still name the same number.
--
-- ### Data
--
-- No backfill, and no column, table, index or trigger. `APP12-M01.A` measured
-- the corpus against all four target invariants and found zero violating rows;
-- STEP 0 re-measures it here rather than trusting that audit, because a
-- migration that silently repaired a violating row would rewrite catalog
-- evidence unreviewed. If any row violates any of the four, this migration
-- fails loudly and changes nothing.

--> STEP 0 — data precheck.
--
-- Each count is over exactly the data the constraints below are about to
-- reject. The set-level rules the domain owns (contiguity, presence of
-- position 0, the 20-item count) are deliberately not checked here: this
-- migration does not install them, so failing on them would block an upgrade
-- for a rule the resulting database still would not enforce.
DO $$
DECLARE
  v_duplicate_asset bigint;
  v_duplicate_position bigint;
  v_position_out_of_range bigint;
  v_primary_role_misplaced bigint;
BEGIN
  SELECT count(*) INTO v_duplicate_asset FROM (
    SELECT 1 FROM product_media GROUP BY product_id, asset_id HAVING count(*) > 1
  ) d;

  SELECT count(*) INTO v_duplicate_position FROM (
    SELECT 1 FROM product_media GROUP BY product_id, display_order HAVING count(*) > 1
  ) d;

  SELECT count(*) INTO v_position_out_of_range
    FROM product_media WHERE display_order < 0 OR display_order >= 20;

  SELECT count(*) INTO v_primary_role_misplaced
    FROM product_media
   WHERE (display_order = 0 AND role <> 'THUMBNAIL')
      OR (display_order > 0 AND role = 'THUMBNAIL');

  IF v_duplicate_asset > 0
     OR v_duplicate_position > 0
     OR v_position_out_of_range > 0
     OR v_primary_role_misplaced > 0 THEN
    RAISE EXCEPTION
      'APP12-M01.DB1 precheck failed: % products repeat an asset, % products repeat a display position, % media rows sit outside 0..19, % media rows place the primary role away from position 0',
      v_duplicate_asset, v_duplicate_position,
      v_position_out_of_range, v_primary_role_misplaced
      USING ERRCODE = '23514';
  END IF;
END
$$;--> statement-breakpoint

--> STEP 1 — one Asset per Product: tighten CST-013 by dropping `role` from it.
ALTER TABLE "product_media" DROP CONSTRAINT "uq_product_media__product_asset_role";--> statement-breakpoint
ALTER TABLE "product_media" ADD CONSTRAINT "uq_product_media__product_asset" UNIQUE("product_id","asset_id");--> statement-breakpoint

--> STEP 2 — one row per position.
ALTER TABLE "product_media" ADD CONSTRAINT "uq_product_media__product_display_order" UNIQUE("product_id","display_order");--> statement-breakpoint

--> STEP 3 — positions are zero-based and bounded by MAX_PRODUCT_MEDIA_ITEMS.
ALTER TABLE "product_media" ADD CONSTRAINT "ck_product_media__display_order_bounded" CHECK ("product_media"."display_order" >= 0 and "product_media"."display_order" < 20);--> statement-breakpoint

--> STEP 4 — the primary role and position 0 imply each other, both ways.
ALTER TABLE "product_media" ADD CONSTRAINT "ck_product_media__primary_role_at_zero" CHECK (("product_media"."display_order" = 0 and "product_media"."role" = 'THUMBNAIL') or ("product_media"."display_order" > 0 and "product_media"."role" <> 'THUMBNAIL'));
