/**
 * Physical identifier primitives (ADR-DB1-007, DB6-S04).
 *
 * Two categories, deliberately different:
 *
 * - **Business/public identity → UUIDv7, generated by the application.** The
 *   caller knows the id before the insert, which keeps aggregates composable
 *   without a database round-trip. UUIDv7 is time-ordered, so inserts append at
 *   the right-hand edge of the B-tree instead of scattering page writes.
 * - **Internal append-only records → `bigint GENERATED ALWAYS AS IDENTITY`.**
 *   Compact 8-byte ordered keys where no external party ever sees the id.
 *
 * These are column *builders*, not a base table: every table still declares its
 * own columns explicitly so the physical schema stays reviewable.
 */
import { bigint, uuid } from 'drizzle-orm/pg-core';
import { uuidv7 } from 'uuidv7';

/**
 * Generates a UUIDv7. The single vetted RFC 9562 source for the whole system —
 * never `Math.random`, never a second library.
 */
export function newId(): string {
  return uuidv7();
}

/** Business/public primary key column. Values come from {@link newId}. */
export function idColumn(name = 'id') {
  return uuid(name);
}

/** Reference to a business entity's UUID primary key. */
export function idReference(name: string) {
  return uuid(name);
}

/** Internal append-only surrogate key, generated by PostgreSQL. */
export function sequenceColumn(name = 'id') {
  return bigint(name, { mode: 'bigint' }).generatedAlwaysAsIdentity();
}
