'use client';

/**
 * The browser-side preview of the exact design under review (`707:40`,
 * `713:3`).
 *
 * ## One `<svg>`, and nothing beside it
 *
 * The stored document is rendered as native SVG by React (`IMP-D026`,
 * `ADR-APP0-001`): no canvas, no rendering-engine dependency, no interaction
 * library, no server rasterization and no preview derivative. The `viewBox` is
 * the document's own placement canvas, so the drawing fills the frame at any
 * width without a single number being recomputed here.
 *
 * ## The watermark is not optional
 *
 * It is mounted unconditionally, as a sibling of the drawing rather than a
 * child of it, so no prop, no state and no branch can render the preview
 * without it. There is no toggle to remove because there is no toggle.
 *
 * ## And there is nothing to take away
 *
 * No download control, no export, no "save image", no copy-JSON, no object URL,
 * no clipboard write and no local persistence of the document in any store. The
 * design exists in this browser's memory for as long as the page is open, and
 * the policy note beside the frame says exactly that and claims nothing about
 * screenshots.
 *
 * ## A document that cannot be drawn is said so, not approximated
 *
 * A validation or geometry refusal renders one honest sentence and no artwork,
 * with no element id, no path and no finding message — a surface refusing to
 * render untrusted data must not put that data on screen while explaining
 * itself. The approve control is not offered over a failed preview: approving
 * artwork nobody could see is the one outcome this screen exists to prevent.
 */
import { useMemo, useRef } from 'react';

import { DESIGN_REVIEW_COPY as COPY } from '../model/design-review-copy';
import { buildReviewScene } from '../model/review-scene';
import { mintReviewWatermarkToken } from '../model/review-watermark';
import { DesignPreviewElement } from './design-preview-element';
import { ReviewWatermark, ReviewWatermarkNotice } from './review-watermark';

export interface DesignPreviewProps {
  /**
   * The stored document, exactly as `APP6-B10` returned it.
   *
   * Typed `unknown` on purpose: the wire type has been through no runtime
   * check, and this component's first act is to hand it to the one validator
   * that decides whether it is a document at all.
   */
  readonly document: unknown;
}

export function DesignPreview({ document }: DesignPreviewProps) {
  const result = useMemo(() => buildReviewScene(document), [document]);
  // One token per mounted review. Minted in a ref rather than during render so
  // it is stable across re-renders and cannot be regenerated by a state change.
  const tokenRef = useRef<string | null>(null);
  tokenRef.current ??= mintReviewWatermarkToken();

  if (!result.ok) {
    return (
      <div className="secure-design-review__preview" data-testid="design-review-preview-failed">
        <p className="secure-design-review__preview-failure">{COPY.preview.failure}</p>
        <p className="secure-design-review__preview-failure-note">{COPY.preview.failureNote}</p>
      </div>
    );
  }

  const { scene } = result;

  return (
    <div className="secure-design-review__preview">
      <div className="secure-design-review__preview-frame" data-testid="design-review-preview">
        <svg
          className="secure-design-review__preview-svg"
          viewBox={`0 0 ${String(scene.canvasWidthPx)} ${String(scene.canvasHeightPx)}`}
          role="img"
          aria-label={COPY.preview.label}
          data-testid="design-review-preview-svg"
        >
          {scene.elements.map((placed) => (
            <DesignPreviewElement key={placed.id} placed={placed} />
          ))}
        </svg>
        <ReviewWatermark token={tokenRef.current} />
      </div>
      <ReviewWatermarkNotice />
    </div>
  );
}

/**
 * Whether a stored document can be drawn at all.
 *
 * Exported so the card can decide whether to offer an approve control without
 * rendering the preview twice or reaching into its internals. Pure, and it is
 * the same call the preview makes.
 */
export function isPreviewRenderable(document: unknown): boolean {
  return buildReviewScene(document).ok;
}
