/**
 * Appending one internal moderation note (`APP5-B05` §3, §8).
 *
 * The smaller of the two moderation mutations, and its whole value is what it
 * does **not** do. A note is an operator writing something down; it moves
 * nothing, notifies nobody and leaves no transition row. There is no branch here
 * that could reach `transition()` — the repository is used through exactly one
 * method — and no outbox recorder is injected, so a note cannot acquire a side
 * effect by a later edit.
 *
 * ### Append-only is a property of the surface, not a convention
 *
 * There is no update method, no delete method and no note id on the way in.
 * TBL-041 has no `updated_at` and DB4 marks it append-only (CST-098): a changed
 * decision is a new note, and the history of what an operator thought is
 * evidence, not a draft.
 *
 * ### Everything identifying is server-derived
 *
 * The Admin id comes from the bound request actor — the one
 * `AuthenticatedAdminGuard` established from the session cookie — and the
 * sequence and timestamp are generated by the database. The command below
 * carries a request id, a kind and a text, and has nowhere to put an actor.
 */
import { Inject, Injectable } from '@nestjs/common';
import { TransactionManager } from '@embroidery/persistence';

import { RequestContextService } from '../../../../platform/request-context/request-context.service';
import { RequestModerationError } from '../../domain/moderation/request-moderation.errors';
import type { App5NoteKind } from '../../domain/moderation/request-moderation.policy';
import {
  CUSTOM_REQUEST_REPOSITORY,
  type CustomRequestId,
  type CustomRequestRepository,
} from '../../domain/repositories/custom-request.repository';
import { requireAdminActorId } from './moderation-actor';

export interface AppendModerationNoteCommand {
  readonly requestId: CustomRequestId;
  readonly kind: App5NoteKind;
  readonly note: string;
}

export interface AppendedModerationNoteView {
  readonly requestId: string;
  readonly sequence: number;
  readonly kind: App5NoteKind;
  readonly adminId: string;
  readonly createdAt: Date;
  /** The status the request still has. Published so a client can see it did not move. */
  readonly requestStatus: string;
}

@Injectable()
export class AppendModerationNoteUseCase {
  constructor(
    private readonly transactions: TransactionManager,
    @Inject(CUSTOM_REQUEST_REPOSITORY) private readonly requests: CustomRequestRepository,
    private readonly requestContext: RequestContextService,
  ) {}

  async append(command: AppendModerationNoteCommand): Promise<AppendedModerationNoteView> {
    const adminId = requireAdminActorId(this.requestContext);

    return this.transactions.runInTransaction(async () => {
      // The FK would refuse an unknown request anyway, but as a constraint
      // violation naming `fk_request_moderation_notes__custom_request_id`. Read
      // first so the operator gets a 404 instead of a sanitised 500, and so the
      // status this call reports back is the one the note was filed against.
      const request = await this.requests.findById(command.requestId);
      if (request === undefined) {
        throw new RequestModerationError('REQUEST_NOT_FOUND');
      }

      const appended = await this.requests.appendModerationNote(
        command.requestId,
        command.kind,
        command.note,
        adminId,
      );

      return {
        requestId: command.requestId,
        sequence: appended.sequence,
        kind: command.kind,
        adminId,
        createdAt: appended.createdAt,
        requestStatus: request.status,
      };
    });
  }
}
