/**
 * Local asset registry. Every asset is generated by `scripts/generate-assets.mjs`
 * and served from `public/assets` — no CDN, no third-party or copyrighted asset,
 * and no original high-resolution file (all documents reference the
 * `editor-preview` derivative only).
 */
export const ASSET_URLS = [
  '/assets/product-front.png',
  '/assets/badge.png',
  '/assets/photo.jpg',
  '/assets/mark.svg',
] as const;

export type AssetRegistry = ReadonlyMap<string, HTMLImageElement>;

function loadImage(url: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const image = new window.Image();
    image.onload = () => {
      resolve(image);
    };
    image.onerror = () => {
      reject(new Error(`Failed to load spike asset ${url}`));
    };
    image.src = url;
  });
}

let cached: AssetRegistry | null = null;

/** Loads every asset once and waits for decode, so no measurement races I/O. */
export async function loadAssets(): Promise<AssetRegistry> {
  if (cached !== null) {
    return cached;
  }
  const entries = await Promise.all(
    ASSET_URLS.map(async (url) => [url, await loadImage(url)] as const),
  );
  cached = new Map(entries);
  return cached;
}

/** Waits for the whitelisted fonts so text metrics are stable before measuring. */
export async function waitForFonts(families: readonly string[]): Promise<void> {
  const fonts = document.fonts;
  await Promise.all(families.map((family) => fonts.load(`16px ${family}`)));
  await fonts.ready;
}
