import { baseConfig } from '@embroidery/eslint-config/base';

const NODE_GLOBALS = {
  process: 'readonly',
  console: 'readonly',
  URL: 'readonly',
  fetch: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  Response: 'readonly',
};

export default [
  // Transient Playwright run artifacts (bundled report/trace assets) must never
  // be linted — they are gitignored and regenerated by every e2e run, so linting
  // them would make `pnpm quality` fail non-deterministically after a run.
  { ignores: ['test-results/**', 'playwright-report/**', '.e2e-state/**', 'coverage/**'] },
  ...baseConfig,
  {
    // Plain-Node orchestration + CLI scripts, run directly with `node` and never
    // bundled into any application — the same class as the root `tools/*.mjs`.
    files: ['scripts/**/*.mjs', 'support/**/*.mjs'],
    languageOptions: {
      globals: NODE_GLOBALS,
    },
  },
];
