import { baseConfig } from '@embroidery/eslint-config/base';

const NODE_GLOBALS = {
  process: 'readonly',
  Buffer: 'readonly',
  console: 'readonly',
  URL: 'readonly',
  fetch: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  Response: 'readonly',
};

export default [
  // Transient Playwright run artifacts (bundled report/trace assets) must never
  // be linted — they are gitignored and regenerated by every e2e run, so linting
  // them would make `pnpm quality` fail non-deterministically after a run.
  { ignores: ['test-results/**', 'playwright-report/**', '.e2e-state/**', 'coverage/**'] },
  ...baseConfig,
  {
    // Plain-Node orchestration + CLI scripts, run directly with `node` and never
    // bundled into any application — the same class as the root `tools/*.mjs`.
    files: ['scripts/**/*.mjs', 'support/**/*.mjs'],
    languageOptions: {
      globals: NODE_GLOBALS,
    },
  },
  {
    // The APP12-H05 Core Web Vitals probe is the one file here that does NOT run
    // in Node: its functions are serialized and evaluated inside Chromium by
    // Playwright, so `window`, `performance` and `PerformanceObserver` are the
    // correct globals for it. Declared for this file alone rather than widened
    // across `support/**`, because an orchestration script reaching for
    // `window` is a real defect and must keep failing.
    files: ['support/app12/h05-cwv-probe.mjs'],
    languageOptions: {
      globals: {
        ...NODE_GLOBALS,
        window: 'readonly',
        performance: 'readonly',
        PerformanceObserver: 'readonly',
      },
    },
  },
  {
    // The `APP12-H08` accessibility helpers are the second such case, and a
    // mixed one: each module runs in **Node** (reading the axe bundle, reading
    // the locked token file, driving the page) and also carries the function
    // bodies Playwright serializes into the browser, where `document`,
    // `window` and `HTMLElement` are the correct globals. Both sets are
    // declared for these two files alone rather than widened across
    // `support/**`, for the reason above: an orchestration script reaching for
    // `document` is a real defect and must keep failing everywhere else.
    // `APP12-V02-C1`'s login-reflow runner is the same mixed shape: it spawns
    // `next start` and drives Chromium from Node, and carries the measurement
    // bodies Playwright serializes into the page.
    files: [
      'support/app12/h08-axe.mjs',
      'support/app12/h08-measure.mjs',
      'support/app12/v02-c1-login-reflow.mjs',
    ],
    languageOptions: {
      globals: {
        ...NODE_GLOBALS,
        window: 'readonly',
        document: 'readonly',
        HTMLElement: 'readonly',
      },
    },
  },
  {
    // The `APP12-V01` UX probe is the third, and the purest of them: its whole
    // body is one `page.evaluate` argument, so it runs **only** in Chromium and
    // never in Node. `Node` (the DOM interface, not the runtime) is declared
    // because the probe distinguishes an element's own text nodes from its
    // descendants' — which is what separates a paragraph from the container
    // around it, and therefore what the whole density measurement rests on.
    files: ['support/app12/v01-ux-probe.mjs'],
    languageOptions: {
      globals: {
        ...NODE_GLOBALS,
        window: 'readonly',
        document: 'readonly',
        HTMLElement: 'readonly',
        Node: 'readonly',
      },
    },
  },
];
